services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: uskill-api
    ports:
      - "8000:8000"
    environment:
      - USKILL_ADMIN_EMAIL=${USKILL_ADMIN_EMAIL}
      - USKILL_ADMIN_PASSWORD=${USKILL_ADMIN_PASSWORD}
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: uskill-app
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - api
