services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: uskill-api
    ports:
      - "${API_PORT}:8000"
    environment:
      - USKILL_ADMIN_EMAIL=${USKILL_ADMIN_EMAIL}
      - USKILL_ADMIN_PASSWORD=${USKILL_ADMIN_PASSWORD}
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
    container_name: uskill-app
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
    depends_on:
      - api
