name: app
description: "U-Skill Wiki"
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^1.0.8

  gap: ^3.0.1
  go_router: ^17.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^9.2.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  dio: ^5.9.2
  flutter_riverpod: ^3.3.2
  flutter_svg: ^2.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logos/Logotype_U-Skill-Wiki_noir-72dpi.png
    - assets/logos/Logotype_Nantes-U_blanc-72dpi.png
    - assets/logos/Logotype_Nantes-U_noir-72dpi.png

    - assets/images/Header-banner.jpg

    - assets/pictos/star-of-life.svg

  fonts:
    - family: Beatrice
      fonts:
        - asset: assets/fonts/beatrice/BeatriceTRIAL-Extrabold.ttf
          weight: 900
        - asset: assets/fonts/beatrice/BeatriceTRIAL-ExtraboldItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/beatrice/BeatriceTRIAL-Bold.ttf
          weight: 700
        - asset: assets/fonts/beatrice/BeatriceTRIAL-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/beatrice/BeatriceTRIAL-Semibold.ttf
          weight: 600
        - asset: assets/fonts/beatrice/BeatriceTRIAL-SemiboldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/beatrice/Beatrice-Medium.ttf
          weight: 500

        - asset: assets/fonts/beatrice/BeatriceTRIAL-Regular.ttf
          weight: 400
        - asset: assets/fonts/beatrice/BeatriceTRIAL-RegularItalic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/beatrice/BeatriceTRIAL-Light.ttf
          weight: 300
        - asset: assets/fonts/beatrice/BeatriceTRIAL-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/beatrice/BeatriceTRIAL-Thin.ttf
          weight: 200
        - asset: assets/fonts/beatrice/BeatriceTRIAL-ThinItalic.ttf
          weight: 200
          style: italic

    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Black.ttf
          weight: 900
        - asset: assets/fonts/source_sans_pro/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/source_sans_pro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_pro/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/source_sans_pro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/source_sans_pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_pro/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
